#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOCS_DIR=$SCRIPT_DIR/../docs
LATEX_OPTS="--variable=colorlinks"

for m in $DOCS_DIR/*.md; do 
	p=`echo $m | sed 's/\.md$/.pdf/'`;
	echo "Converting $m to $p";
	pandoc -f markdown_github $LATEX_OPTS -o $p $m
done